### ISSUE TITLE
Update needed for the OSCAL Project Structure page

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL-Pages#26]
The page describing OSCAL-related projects ( https://pages.nist.gov/OSCAL/about/projects/) has old/ obsolete content and requires update for all user to better understand where can they find OSCAL resources. In the process, broken internal links need to be fixed.
https://pages.nist.gov/OSCAL/about/projects/#Metaschema should be https://pages.nist.gov/OSCAL/about/projects/#metaschema\
[Metaschema-Java](https://pages.nist.gov/OSCAL/about/projects/#Metaschema-Java) should be https://pages.nist.gov/OSCAL/about/projects/#metaschema-java, etc.

**Comment by aj-stein-nist** [comment]
It appears this issue was already fixed in a series of PRs, specifically https://github.com/usnistgov/OSCAL-Pages/pull/28 as part of https://github.com/usnistgov/OSCAL-Pages/pull/27.
