### ISSUE TITLE
Pages that require additional review and corrections based on new artifacts in OSCAL

### ISSUE THREAD

**Issue by Compton-NIST** [usnistgov/OSCAL-Pages#27]
These files need review:

```
./src/content/concepts/layer/assessment/assessment-plan/_index.md
./src/content/concepts/layer/assessment/assessment-results/_index.md
./src/content/concepts/layer/assessment/poam/_index.md
./src/content/concepts/layer/control/catalog/_index.md
./src/content/concepts/layer/control/profile/_index.md
./src/content/concepts/layer/implementation/component-definition/_index.md
./src/content/concepts/layer/implementation/ssp/_index.md
./src/content/concepts/layer/overview.md
./src/content/learn/tutorials/general/releases.md
./src/content/tools/_index.md
```

They contain content that links to the json/xml schema documents in source, but it may not always be a simple url fix.  It may require some adjustment of the content to match the link.  

For now, we are linking schema and converter artifacts as v1.1.0 release content.  This is required to specifically link to a json, xml, xsd, etc.  A fix will be coming for this soon, but we are hard coding to the version for now. 

In some cases, when the reference is generally to all artifacts, a link to https://github.com/usnistgov/OSCAL/releases/latest may be sufficient.

Lastly, there are some links to the old readme on how to use the converter. [See README from v1.0.5](https://github.com/usnistgov/OSCAL/blob/release-1.0.5/json/README.md)  This document may need to be brought over into the website for those links to reference.  `./src/content/concepts/layer/control/profile/_index.md:18`is has an example under the **How do I use this?** link.

**Comment by Compton-NIST** [comment]
@aj-stein-nist Question on this one is if we need to bring over the readme that was deleted from OSCAL, or if there are revised directions/links needed based on the `Makefile` approach we've moved to.

**Comment by aj-stein-nist** [comment]
Forward this to Sprint 74 and consult with @nikitawootten-nist  when available.
