### ISSUE TITLE
Aliases to old pages used within OSCAL model documentation

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/OSCAL-Pages#50]
The following URLs are used within OSCAL model documentation (*in* the metaschemas):
- https://pages.nist.gov/OSCAL/concepts/layer/implementation/component-definition/
- https://pages.nist.gov/OSCAL/concepts/layer/overview/#modeling-approach
- https://pages.nist.gov/OSCAL/concepts/uri-use/#absolute-uri
- https://pages.nist.gov/OSCAL/concepts/uri-use/#linking-to-another-oscal-object
- https://pages.nist.gov/OSCAL/concepts/uri-use/#relative-reference
- https://pages.nist.gov/OSCAL/concepts/uri-use/#use-as-a-naming-system-identifier

These URLs contribute to 554 total dead links within the OSCAL Reference

**Comment by aj-stein-nist** [comment]
Since this is an important page and a low effort PR you just published, I will bring this into sprint. Thanks for bringing this to our attention, @nikitawootten-nist!
